# nextjs x nestjs x postgresql x prisma x swagger
services:
  web:
    build:
      context: ./web
      dockerfile: ../dockerfile/Dockerfile.web
    ports:
      - 3000:3000
    volumes:
      - ./web:/web
    env_file:
      - ./web/.env
    networks:
      - app-network
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: ../dockerfile/Dockerfile.api
    ports:
      - 3001:3001
      - 5555:5555
    volumes:
      - ./api:/api
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=deatheater
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    env_file:
      - api/.env
    ports:
      - 5432:5432
    networks:
      - app-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    platform: linux/amd64  # 追加
    ports:
      - "8002:8080"
    volumes:
      - ./docs/openapi.yaml:/docs/openapi.yaml
    environment:
      SWAGGER_JSON: /docs/openapi.yaml
    depends_on:
      - api

networks:
  app-network:
    driver: bridge
