# nextjs
FROM node:22.9.0

# Create app directory
WORKDIR /web

# Install app dependencies
RUN npm i -g npm@latest && npm i -g pnpm@latest
COPY ./package.json ./package.json
RUN pnpm install

USER node

# Bundle app source
COPY --chown=node:node . .

# Expose port and start application
EXPOSE 3000

CMD ["pnpm", "dev"]
