# Next.js
FROM node:22.9.0 as deps

# Create app directory
WORKDIR /web
# Install global dependencies
RUN npm i -g npm@latest pnpm@latest
# Copy only package.json and pnpm-lock.yaml for caching dependency layers
COPY package.json ./
# Install dependencies
RUN pnpm install

FROM node:22.9.0 as builder

WORKDIR /web
# Install pnpm in builder stage
RUN npm i -g pnpm@latest
# Copy the rest of the application code
COPY . .
COPY --from=deps /web/node_modules ./node_modules
RUN pnpm build

FROM node:22.9.0
WORKDIR /web
ENV NODE_ENV production
# Copy the necessary build output
COPY --from=builder /web/public ./public
COPY --from=builder /web/.next ./.next
COPY --from=builder /web/package.json ./package.json
# Install pnpm in final stage
RUN npm i -g pnpm@latest
EXPOSE 3000
CMD [ "pnpm", "dev" ]
